-- AllPredictor BETA AI 24/7 storage
create extension if not exists pg_cron;
create extension if not exists pg_net;

create table if not exists public.beta_ai_rounds (
  id bigint generated by default as identity primary key,
  round_key text not null unique,
  coefficient numeric(12,2) not null,
  source_time text,
  raw jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.beta_ai_signals (
  id bigint generated by default as identity primary key,
  target numeric(12,2) not null,
  status text not null default 'open' check (status in ('open','win','loss')),
  checked_rounds integer not null default 0,
  result_coefficient numeric(12,2),
  source_round_id bigint references public.beta_ai_rounds(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists beta_ai_rounds_created_idx on public.beta_ai_rounds(created_at desc);
create index if not exists beta_ai_signals_created_idx on public.beta_ai_signals(created_at desc);
create unique index if not exists beta_ai_one_open_signal on public.beta_ai_signals ((status)) where status='open';

alter table public.beta_ai_rounds enable row level security;
alter table public.beta_ai_signals enable row level security;

drop policy if exists "beta ai public read rounds" on public.beta_ai_rounds;
create policy "beta ai public read rounds" on public.beta_ai_rounds for select using (true);
drop policy if exists "beta ai public read signals" on public.beta_ai_signals;
create policy "beta ai public read signals" on public.beta_ai_signals for select using (true);

grant select on public.beta_ai_rounds, public.beta_ai_signals to anon, authenticated;

-- Replace YOUR_CRON_SECRET with the same value saved in Edge Function Secrets
-- under BETA_AI_CRON_SECRET, then run this block once.
select cron.unschedule(jobid) from cron.job where jobname = 'allpredictor-beta-ai-minute';
select cron.schedule(
  'allpredictor-beta-ai-minute',
  '* * * * *',
  $$
  select net.http_post(
    url := 'https://lcgewatmbpfxzoiqneoa.supabase.co/functions/v1/beta-ai-worker',
    headers := jsonb_build_object('Content-Type','application/json','x-cron-secret','YOUR_CRON_SECRET'),
    body := '{}'::jsonb
  );
  $$
);
