project_id = "xlidiojdbozxikjloiaj"

[functions.track-user]
verify_jwt = false

[functions.activate-license]
verify_jwt = false

[functions.check-license]
verify_jwt = false

[functions.admin-api]
verify_jwt = false

[functions.notify-expiring]
verify_jwt = false

[functions.allpredictor-api]
verify_jwt = false

[functions.beta-ai-worker]
verify_jwt = false
