(()=>{'use strict';
const el=id=>document.getElementById(id),labels={pending:'Проверяется',hit:'Попадание',miss:'Промах',unknown:'Не проверено',late:'Ответ опоздал',observe:'Наблюдение',error:'Ошибка ИИ'};
let busy=false,last=null,settingsLoaded=false;
const time=t=>t?new Date(t*1000).toLocaleTimeString('ru-RU',{timeZone:'Europe/Kyiv',hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';
function render(d){last=d;el('beeStatus').textContent=d.message+' · '+(d.model||'модель не выбрана');const p=d.predictions?.[0];el('beeTarget').textContent=p?.target?p.target.toFixed(2)+'×':'Нет цели';el('beeWindow').textContent=p?.target?(p.status==='pending'?Math.max(0,p.horizon-(p.observed||0))+' из '+p.horizon+' осталось':p.horizon+' раундов · окно закрыто'):'—';el('beeResult').textContent=labels[p?.status]||'Ожидание';el('beeTime').textContent=time(p?.created_at);el('beeReason').textContent=p?.explanation||'Ожидаю достаточные свежие данные облачного сборщика Supabase.';el('beeToggle').textContent=d.enabled?'Пауза ИИ':'Включить ИИ';if(!settingsLoaded){el('beePersona').value=d.persona||'';el('beeKnowledge').value=d.knowledge||'';settingsLoaded=true;}el('beeStats').textContent=(d.stats||[]).map(s=>'≥'+s.target+'× / '+s.horizon+' раундов: '+s.hits+' попаданий, '+s.misses+' промахов, '+s.unknown+' не проверено').join(' · ')||'Проверенных прогнозов пока нет.';el('beeStats').textContent+=' · Облачный период; прежний журнал сохранён: '+(d.legacy_count||0)+' записей · Ошибки среди последних 100 запросов: '+(d.recent_errors||0);el('beeJournal').replaceChildren();for(const p of (d.predictions||[]).slice(0,25)){const row=document.createElement('p');row.className='signal-note';row.textContent=time(p.created_at)+' · '+(p.target?'≥'+p.target+'× / '+p.horizon+' раунда':'Без цели')+' · '+(labels[p.status]||p.status)+(p.actual?' · факт '+p.actual+'×':'')+' · ID '+p.id;el('beeJournal').append(row)}}
async function refresh(){if(busy)return;busy=true;try{render(await BeeCloud.request())}catch(e){el('beeStatus').textContent=e.message;el('beeTarget').textContent='—';el('beeResult').textContent='Связь не подтверждена'}finally{busy=false}}
async function change(body){try{render(await BeeCloud.request('POST',body))}catch(e){el('beeStatus').textContent=e.message}}
el('beeRefresh').addEventListener('click',refresh);el('beeToggle').addEventListener('click',()=>change({enabled:!last?.enabled}));el('beeSave').addEventListener('click',()=>change({persona:el('beePersona').value,knowledge:el('beeKnowledge').value}));window.addEventListener('bee-cloud-connect',refresh);document.addEventListener('visibilitychange',()=>{if(!document.hidden)refresh()});refresh();setInterval(refresh,5000);
})();

