(()=>{
'use strict';
const FRAME=document.getElementById('oldApp');
const BRIDGE=document.getElementById('bridgeState');
const TARGETS=[1.5,2,3,5,10];
const ANALYZE_N=8;
const HORIZON=3;
const POLL_MS=5000;
const V2_COUNTS='luckyjet_clone_v2_counts';
const V2_HISTORY='luckyjet_clone_v2_history';
const V2_MODE='luckyjet_v2_mode';
const MODES={
  SAFE:{minRows:180,minP:.72,minEdge:.045,minAgree:4,minHealth:72,maxPerm:.15,ciFloor:0},
  PRO:{minRows:90,minP:.62,minEdge:.020,minAgree:3,minHealth:55,maxPerm:.28,ciFloor:-.01},
  EXPERIMENTAL:{minRows:35,minP:.55,minEdge:.005,minAgree:2,minHealth:38,maxPerm:.45,ciFloor:-.035}
};
let doc=null,win=null,cfg=null,lastRows=[],lastState=null,lastAnalysis=null;
let active=null,pollTimer=null,auto=false,busy=false;

const mean=a=>a.length?a.reduce((s,v)=>s+v,0)/a.length:0;
const pct=v=>Number.isFinite(v)?(v*100).toFixed(1)+'%':'—';
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const median=a=>{if(!a.length)return 0;const s=a.slice().sort((x,y)=>x-y),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2};
const mad=a=>{if(!a.length)return 0;const m=median(a);return median(a.map(v=>Math.abs(v-m)))};
function q(a,p){if(!a.length)return 0;const s=a.slice().sort((x,y)=>x-y),i=(s.length-1)*p,l=Math.floor(i),h=Math.ceil(i);return l===h?s[l]:s[l]+(s[h]-s[l])*(i-l)}
function kyiv(ts,sec=false){try{return new Intl.DateTimeFormat('ru-RU',{timeZone:'Europe/Kyiv',hour:'2-digit',minute:'2-digit',second:sec?'2-digit':undefined,hour12:false}).format(new Date(ts))}catch{return new Date(ts).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}}
function setBridge(t){if(BRIDGE)BRIDGE.textContent=t}
function el(id){return doc&&doc.getElementById(id)}
function setStatus(t,kind=''){const x=el('verifyStatus');if(!x)return;x.className='status '+kind;x.textContent=t}
function getMode(){const m=localStorage.getItem(V2_MODE)||'PRO';return MODES[m]?m:'PRO'}
function setMode(m){if(MODES[m])localStorage.setItem(V2_MODE,m)}
function getRange(){try{const x=JSON.parse(localStorage.getItem('kk_pred_range_v1')||'{}');const min=Number(x.min),max=Number(x.max);return{min:Number.isFinite(min)?min:2,max:Number.isFinite(max)?max:8}}catch{return{min:2,max:8}}}
function counts(){try{const x=JSON.parse(localStorage.getItem(V2_COUNTS)||'{}');return{ok:Number(x.ok)||0,ko:Number(x.ko)||0}}catch{return{ok:0,ko:0}}}
function saveCounts(c){localStorage.setItem(V2_COUNTS,JSON.stringify(c));renderCounts()}
function hist(){try{const x=JSON.parse(localStorage.getItem(V2_HISTORY)||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
function saveHist(x){localStorage.setItem(V2_HISTORY,JSON.stringify(x.slice(0,300)))}
function renderCounts(){const c=counts();if(el('countOk'))el('countOk').textContent=c.ok;if(el('countKo'))el('countKo').textContent=c.ko;if(el('countTotal'))el('countTotal').textContent=c.ok+c.ko}
function renderHistory(){const box=el('chipsContainer');if(!box)return;const h=hist();box.innerHTML='';if(!h.length){const d=doc.createElement('div');d.textContent='Прогнозов V2 пока нет.';d.style.opacity='.85';box.appendChild(d);return}h.forEach(z=>{const d=doc.createElement('div');d.className='chip '+(z.status==='ok'?'ok':'ko');const extra=z.health!=null?` • Health ${z.health}`:'';d.innerHTML='<div>'+Number(z.target).toFixed(2)+'x</div><small>'+(z.status==='ok'?'Зашло':'Не зашло')+' • '+kyiv(z.time)+extra+'</small>';box.appendChild(d)})}
function openPanel(id){const p=el(id);if(p)p.classList.add('open')}

function arrFrom(data){if(Array.isArray(data))return data;if(!data||typeof data!=='object')return[];for(const k of ['data','history','results','items','rounds']){if(Array.isArray(data[k]))return data[k];if(data[k]&&Array.isArray(data[k].data))return data[k].data}return[]}
function coefOf(x){if(!x||typeof x!=='object')return null;let v=x.topCoefficient??x.coef??x.crash??x.value??x.multiplier;if(v==null&&Array.isArray(x.finalValues)&&x.finalValues.length)v=x.finalValues[0];v=Number(v);return Number.isFinite(v)&&v>=1?v:null}
function timeOf(x){for(const k of ['endedAt','ended_at','createdAt','created_at','timestamp','time','date','updated_at']){let v=x?.[k];if(v==null)continue;if(typeof v==='number'){if(v<1e12)v*=1000;if(Number.isFinite(v))return v}const t=Date.parse(v);if(Number.isFinite(t))return t}return null}
function idOf(x,i){return String(x?.id??x?.round_id??x?.roundId??x?.roundConfig?.id??x?.hash??x?.provablyFair?.hash??('row-'+i+'-'+coefOf(x)))}
function normalize(raw){const out=[],seen=new Set();let dupes=0;raw.forEach((x,i)=>{const coef=coefOf(x);if(coef==null)return;const id=idOf(x,i);if(seen.has(id)){dupes++;return}seen.add(id);out.push({id,coef,ts:timeOf(x)})});const timed=out.filter(x=>Number.isFinite(x.ts)).length;if(out.length&&timed/out.length>.65)out.sort((a,b)=>(a.ts||0)-(b.ts||0));else out.reverse();out.dupes=dupes;return out}
async function fetchJSON(url,opt={}){const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),14000);try{const r=await fetch(url,{...opt,cache:'no-store',signal:ctl.signal});if(!r.ok)throw Error('HTTP '+r.status);return await r.json()}finally{clearTimeout(timer)}}
async function config(){if(cfg)return cfg;const html=await fetch('../ru-ukraine/index.html?cfg='+Date.now(),{cache:'no-store'}).then(r=>{if(!r.ok)throw Error('Не удалось прочитать подключение старой версии');return r.text()});const m=re=>html.match(re)?.[1]||'';cfg={base:m(/const\s+BASE\s*=\s*['\"]([^'\"]+)/),apiKey:m(/const\s+API_KEY\s*=\s*['\"]([^'\"]+)/),direct:m(/const\s+DIRECT_HISTORY_URL\s*=\s*['\"]([^'\"]+)/),customer:m(/['\"]customer-id['\"]\s*:\s*['\"]([^'\"]+)/),session:m(/['\"]session-id['\"]\s*:\s*['\"]([^'\"]+)/)};return cfg}
function domRows(){if(!doc)return[];const xs=[...doc.querySelectorAll('#recentCoefficients .recent-coef')].map(x=>Number(String(x.textContent).replace(/[^0-9.]/g,''))).filter(Number.isFinite);return xs.reverse().map((coef,i)=>({id:'dom-'+i+'-'+coef.toFixed(2),coef,ts:null}))}
function domSignature(){if(!doc)return'';return[...doc.querySelectorAll('#recentCoefficients .recent-coef')].map(x=>x.textContent.trim()).join('|')}
async function loadRows(){const c=await config(),jobs=[];
 if(c.direct&&c.customer&&c.session){for(const s of ['?limit=2000',''])jobs.push((async()=>({source:'DIRECT LIVE',rows:normalize(arrFrom(await fetchJSON(c.direct+s,{headers:{'customer-id':c.customer,'session-id':c.session,'accept':'application/json'}})))}))())}
 if(c.base&&c.apiKey){for(const n of [2000,1000,500,250,100,20])jobs.push((async()=>({source:'AllPredictor API',rows:normalize(arrFrom(await fetchJSON(c.base+'/luckyjet/coefficients?limit='+n,{headers:{'X-API-Key':c.apiKey}})))}))())}
 const settled=await Promise.allSettled(jobs);const ok=settled.filter(x=>x.status==='fulfilled'&&x.value.rows.length>=ANALYZE_N).map(x=>x.value);if(ok.length){ok.sort((a,b)=>b.rows.length-a.rows.length);return{...ok[0],signature:ok[0].rows.slice(-12).map(x=>x.id).join('|')}}
 const dr=domRows();if(dr.length>=ANALYZE_N)return{source:'LIVE интерфейс старой версии',rows:dr,signature:domSignature()};throw Error('Нет 8 завершённых коэффициентов')}
function renderRecent(rows){const box=el('recentCoefficients');if(!box)return;box.innerHTML='';rows.slice(-10).reverse().forEach(r=>{const s=doc.createElement('span');s.className='recent-coef'+(r.coef>=10?' high':r.coef>=2?' mid':'');s.textContent=r.coef.toFixed(2)+'X';box.appendChild(s)})}

function lowStreak(a){let n=0;for(let i=a.length-1;i>=0&&a[i]<=1.3;i--)n++;return n}
function since(a,t){for(let i=a.length-1;i>=0;i--)if(a[i]>=t)return a.length-1-i;return 999}
function horizonBase(p){return 1-Math.pow(1-clamp(p,0,1),HORIZON)}
function hitNext(v,t,target){for(let j=0;j<HORIZON;j++)if(v[t+j]>=target)return 1;return 0}
function betaRate(h,n,priorP,priorN=20){return (h+priorP*priorN)/(n+priorN)}
function bucket(x){return x<1.3?0:x<2?1:x<5?2:x<10?3:4}
function patternDescriptor(a){const logs=a.map(x=>Math.log(Math.min(50,Math.max(1,x)))),m=median(logs),scale=Math.max(.12,mad(logs));return{z:logs.map(x=>clamp((x-m)/scale,-3,3)),b:a.map(bucket),med:median(a),hi2:a.filter(x=>x>=2).length,hi5:a.filter(x=>x>=5).length,low:a.filter(x=>x<=1.3).length}}
function patternDistance(A,B){let shape=0,buck=0;for(let i=0;i<ANALYZE_N;i++){shape+=Math.abs(A.z[i]-B.z[i]);buck+=A.b[i]===B.b[i]?0:1}shape/=ANALYZE_N;buck/=ANALYZE_N;const med=Math.abs(Math.log(Math.max(1,A.med))-Math.log(Math.max(1,B.med)));const counts=(Math.abs(A.hi2-B.hi2)+1.5*Math.abs(A.hi5-B.hi5)+Math.abs(A.low-B.low))/ANALYZE_N;return .52*shape+.22*buck+.14*med+.12*counts}
function wilson(w,n,z=1.96){if(!n)return{lo:0,hi:1};const p=w/n,zz=z*z,den=1+zz/n,c=(p+zz/(2*n))/den,a=z*Math.sqrt((p*(1-p)+zz/(4*n))/n)/den;return{lo:Math.max(0,c-a),hi:Math.min(1,c+a)}}
function stateKey(a,target){const hits=a.filter(x=>x>=target).length,low=lowStreak(a),s5=since(a,5),med=median(a),spread=mad(a);return[hits>=4?'H4':hits>=2?'H2':'H0',low>=3?'L3':low>=1?'L1':'L0',s5<=3?'F3':s5<=7?'F7':'F8',med>=2?'M2':med>=1.5?'M15':'M1',spread>.65?'VH':'VL'].join('|')}

function modelLong(v,target,baseSingle){const a=v.slice(0,-ANALYZE_N),w=a.slice(-Math.min(500,a.length)),h=w.filter(x=>x>=target).length,p=betaRate(h,w.length,baseSingle,40);return{p:horizonBase(p),n:w.length,name:'LONG 500'}}
function modelRecent(v,target,baseSingle){const a=v.slice(0,-ANALYZE_N),w=a.slice(-Math.min(50,a.length)),h=w.filter(x=>x>=target).length,p=betaRate(h,w.length,baseSingle,28);return{p:horizonBase(p),n:w.length,name:'RECENT 50'}}
function modelEWMA(v,target,baseSingle){const a=v.slice(0,-ANALYZE_N).slice(-180);if(!a.length)return{p:horizonBase(baseSingle),n:0,name:'EWMA'};let e=baseSingle,alpha=.075;for(const x of a)e=alpha*(x>=target?1:0)+(1-alpha)*e;const shr=(e*a.length+baseSingle*35)/(a.length+35);return{p:horizonBase(shr),n:a.length,name:'EWMA'}}
function modelState(v,target,baseline){const end=v.length-ANALYZE_N,cur=stateKey(v.slice(end),target);let n=0,h=0;for(let t=ANALYZE_N;t+HORIZON<=end;t++){if(stateKey(v.slice(t-ANALYZE_N,t),target)!==cur)continue;n++;h+=hitNext(v,t,target)}const p=betaRate(h,n,baseline,22),ci=wilson(h,n);return{p,n,h,ci,name:'STATE 8'}}
function modelPattern(v,target,baseline){const end=v.length-ANALYZE_N;if(end<ANALYZE_N+HORIZON)return{p:baseline,n:0,h:0,quality:0,eff:0,avgD:99,candidates:[],name:'PATTERN 8'};const cur=patternDescriptor(v.slice(end)),c=[];for(let t=ANALYZE_N;t+HORIZON<=end;t++){const d=patternDistance(cur,patternDescriptor(v.slice(t-ANALYZE_N,t))),y=hitNext(v,t,target);c.push({d,y,t})}c.sort((a,b)=>a.d-b.d);const k=Math.min(90,Math.max(14,Math.round(c.length*.15))),near=c.slice(0,k);let sw=0,wy=0;for(const x of near){const w=Math.exp(-1.6*x.d);sw+=w;wy+=w*x.y}const h=near.reduce((s,x)=>s+x.y,0),raw=sw?wy/sw:baseline,quality=clamp(Math.exp(-.72*mean(near.map(x=>x.d))),0,1),p=(raw*sw+baseline*22)/(sw+22);return{p,n:near.length,h,quality,eff:sw,avgD:mean(near.map(x=>x.d)),candidates:near,name:'PATTERN 8'}}
function modelRegime(v,target,baseSingle){const past=v.slice(0,-ANALYZE_N),a=past.slice(-100),b=past.slice(-300,-100);if(a.length<20)return{p:horizonBase(baseSingle),n:a.length,name:'REGIME'};const ha=mean(a.map(x=>x>=target?1:0)),hb=b.length?mean(b.map(x=>x>=target?1:0)):baseSingle;const volA=mad(a),volB=b.length?mad(b):volA;const shift=clamp(Math.abs(ha-hb)*1.4+Math.abs(volA-volB)*.06,0,.35),blend=clamp(.62-shift,.25,.62),single=blend*ha+(1-blend)*baseSingle;return{p:horizonBase(single),n:a.length,shift,name:'REGIME'}}

function hashSeed(s){let h=2166136261>>>0;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return h>>>0}
function rng(seed){let x=seed||2463534242;return()=>{x^=x<<13;x^=x>>>17;x^=x<<5;return(x>>>0)/4294967296}}
function permutation(pattern,baseline,seed){const c=pattern.candidates||[],n=c.length;if(n<12)return{pValue:1,iterations:0,observed:pattern.p-baseline};const weights=c.map(x=>Math.exp(-1.6*x.d)),ys=c.map(x=>x.y),sw=weights.reduce((a,b)=>a+b,0);const obs=(weights.reduce((s,w,i)=>s+w*ys[i],0)/sw)-baseline;const R=n>60?180:120,rand=rng(seed),tmp=ys.slice();let ge=0;for(let r=0;r<R;r++){for(let i=tmp.length-1;i>0;i--){const j=Math.floor(rand()*(i+1)),z=tmp[i];tmp[i]=tmp[j];tmp[j]=z}const e=(weights.reduce((s,w,i)=>s+w*tmp[i],0)/sw)-baseline;if(e>=obs-1e-12)ge++}return{pValue:(ge+1)/(R+1),iterations:R,observed:obs}}
function edgeCI(prob,baseline,effN,baseN){const n=Math.max(12,effN||12),bn=Math.max(30,baseN||30),se=Math.sqrt(prob*(1-prob)/n+baseline*(1-baseline)/bn),z=1.96;return{lo:prob-baseline-z*se,hi:prob-baseline+z*se,se}}
function healthScore(x,rows){let s=0;s+=clamp(rows.length/300,0,1)*20;s+=clamp(x.agreement/5,0,1)*22;s+=(x.ci.lo>0?20:x.ci.lo>-.02?10:2);s+=(x.perm.pValue<=.10?20:x.perm.pValue<=.25?13:x.perm.pValue<=.45?6:0);s+=clamp(x.pattern.quality,0,1)*10;s+=clamp(x.pattern.n/45,0,1)*8;return Math.round(clamp(s,0,100))}
function grade(h){return h>=80?'A':h>=65?'B':h>=50?'C':'PAUSE'}
function analyzeTarget(v,target,seedText){const train=v.slice(0,-ANALYZE_N),baseSingle=train.length?mean(train.map(x=>x>=target?1:0)):mean(v.map(x=>x>=target?1:0)),baseline=horizonBase(baseSingle);const m1=modelLong(v,target,baseSingle),m2=modelRecent(v,target,baseSingle),m3=modelEWMA(v,target,baseSingle),m4=modelState(v,target,baseline),m5=modelPattern(v,target,baseline),m6=modelRegime(v,target,baseSingle);const models=[m1,m2,m3,m4,m5,m6],weights=[.14,.15,.13,.20,.25,.13];let prob=0;models.forEach((m,i)=>prob+=m.p*weights[i]);prob=clamp(prob,.01,.995);const agreement=models.filter(m=>m.p>baseline+.004).length;const eff=Math.max(18,Math.min(450,m4.n+(m5.eff||0)+Math.min(120,m2.n*.35))),ci=edgeCI(prob,baseline,eff,Math.min(800,train.length));const perm=permutation(m5,baseline,hashSeed(seedText+'|'+target));const out={target,prob,baseline,edge:prob-baseline,agreement,models,state:m4,pattern:m5,regime:m6,ci,perm,effN:eff};out.health=healthScore(out,v);out.grade=grade(out.health);return out}
function choose(rows){const v=rows.map(r=>r.coef),range=getRange(),mode=getMode(),cfgm=MODES[mode],targets=TARGETS.filter(t=>t>=range.min-1e-9&&t<=range.max+1e-9),ts=targets.length?targets:[clamp(range.min,1.01,10)],seed=rows.slice(-20).map(r=>r.id).join('|');const res=ts.map(t=>analyzeTarget(v,t,seed));res.sort((a,b)=>((b.edge*1.6)+(b.health/100)*.12+b.prob*.08)-((a.edge*1.6)+(a.health/100)*.12+a.prob*.08));const best=res[0];const pass=!!best&&rows.length>=cfgm.minRows&&best.prob>=cfgm.minP&&best.edge>=cfgm.minEdge&&best.agreement>=cfgm.minAgree&&best.health>=cfgm.minHealth&&best.perm.pValue<=cfgm.maxPerm&&best.ci.lo>=cfgm.ciFloor;return{best,res,pass,mode,cfg:cfgm}}

function injectPanels(){if(!doc||el('v2QualityPanel'))return;const style=doc.createElement('style');style.textContent=`#v2QualityPanel{width:100%;max-width:560px;background:rgba(255,255,255,.07);border:1px solid rgba(54,125,231,.45);border-radius:10px;padding:10px 12px;display:flex;flex-direction:column;gap:8px}#v2QualityPanel .q-head{display:flex;align-items:center;justify-content:space-between;gap:8px;font-size:12px;font-weight:900;letter-spacing:.6px}#v2QualityPanel select{background:#111827;color:white;border:1px solid rgba(255,255,255,.18);border-radius:7px;padding:5px 7px;font-weight:800}#v2QualityPanel .q-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px}#v2QualityPanel .q-cell{background:rgba(0,0,0,.18);border-radius:8px;padding:7px;text-align:center}#v2QualityPanel .q-cell small{display:block;font-size:10px;opacity:.72}#v2QualityPanel .q-cell b{display:block;margin-top:3px;font-size:13px}#v2QualityPanel .q-note{font-size:10.5px;line-height:1.4;opacity:.84}@media(max-width:520px){#v2QualityPanel .q-grid{grid-template-columns:repeat(2,1fr)}}`;doc.head.appendChild(style);const p=doc.createElement('div');p.id='v2QualityPanel';p.innerHTML='<div class="q-head"><span>V2 • MODEL HEALTH</span><select id="v2Mode"><option>SAFE</option><option>PRO</option><option>EXPERIMENTAL</option></select></div><div class="q-grid"><div class="q-cell"><small>Health</small><b id="v2Health">—</b></div><div class="q-cell"><small>Ансамбль</small><b id="v2Agree">—</b></div><div class="q-cell"><small>95% CI edge</small><b id="v2CI">—</b></div><div class="q-cell"><small>Permutation p</small><b id="v2Perm">—</b></div><div class="q-cell"><small>Похожих 8</small><b id="v2PatternN">—</b></div><div class="q-cell"><small>Pattern P</small><b id="v2PatternP">—</b></div></div><div class="q-note" id="v2QualityNote">Ансамбль сравнивает 6 независимых оценок. Сигнал проходит только когда достаточно моделей согласны, интервал edge не слишком слабый и permutation-test не показывает обычный шум.</div>';const recent=doc.querySelector('.recent-feed');if(recent&&recent.parentNode)recent.parentNode.insertBefore(p,recent.nextSibling);else{const meta=doc.querySelector('.meta');if(meta&&meta.parentNode)meta.parentNode.insertBefore(p,meta)}const sel=el('v2Mode');if(sel){sel.value=getMode();sel.onchange=()=>{setMode(sel.value);if(lastRows.length>=ANALYZE_N){const o=choose(lastRows);lastAnalysis=o;renderQuality(o.best,o);setStatus('Режим V2: '+o.mode+'. Нажмите РУЧНОЙ СИГНАЛ для нового расчёта.','')}}}}
function renderQuality(best,out){injectPanels();if(!best)return;const health=el('v2Health');if(health){health.textContent=best.health+'/100 • '+best.grade;health.style.color=best.health>=65?'#10b981':best.health>=50?'#f59e0b':'#ef4444'}if(el('v2Agree'))el('v2Agree').textContent=best.agreement+'/6';if(el('v2CI')){el('v2CI').textContent=(best.ci.lo>=0?'+':'')+pct(best.ci.lo)+' … '+(best.ci.hi>=0?'+':'')+pct(best.ci.hi);el('v2CI').style.color=best.ci.lo>0?'#10b981':'#f59e0b'}if(el('v2Perm')){el('v2Perm').textContent=best.perm.iterations?best.perm.pValue.toFixed(3):'—';el('v2Perm').style.color=best.perm.pValue<=.15?'#10b981':best.perm.pValue<=.35?'#f59e0b':'#ef4444'}if(el('v2PatternN'))el('v2PatternN').textContent=best.pattern.n||'—';if(el('v2PatternP'))el('v2PatternP').textContent=best.pattern.n?pct(best.pattern.p):'—';if(el('v2QualityNote'))el('v2QualityNote').textContent='Цель '+best.target.toFixed(2)+'X • P '+pct(best.prob)+' • baseline '+pct(best.baseline)+' • edge '+(best.edge>=0?'+':'')+pct(best.edge)+' • режим '+(out?.mode||getMode())+' • Pattern similarity '+Math.round((best.pattern.quality||0)*100)+'%.'}
function resetQuality(){injectPanels();for(const id of ['v2Health','v2Agree','v2CI','v2Perm','v2PatternN','v2PatternP'])if(el(id))el(id).textContent='—'}

function renderCollect(rows,source){renderRecent(rows);const n=Math.min(ANALYZE_N,rows.length);setBridge('V2 • '+source+' • '+n+'/'+ANALYZE_N);const mb=el('mbText'),dot=el('mbDot');if(mb)mb.textContent='V2 LIVE • '+rows.length+' раундов • анализ последних 8';if(dot)dot.className='mb-dot '+(n>=ANALYZE_N?'safe':'warn');if(el('roundStatus')&&!active)el('roundStatus').textContent=n<ANALYZE_N?String(n):'0';if(n<ANALYZE_N){resetQuality();if(el('multiplier'))el('multiplier').textContent='СБОР '+n+'/'+ANALYZE_N;setStatus('Собираем '+ANALYZE_N+' завершённых коэффициентов для V2','')}}
function setMainButton(){const b=el('generateButton');if(!b)return;b.disabled=busy;b.classList.toggle('cancel',!!active);b.textContent=busy?'АНАЛИЗ 6 МОДЕЛЕЙ...':active?'ОТМЕНИТЬ СИГНАЛ':'РУЧНОЙ СИГНАЛ'}
function countdown(){if(!active)return;const c=el('countdown');if(!c)return;const d=active.when-Date.now();if(d>0){const s=Math.ceil(d/1000);c.textContent='До времени входа: '+Math.floor(s/60)+':'+String(s%60).padStart(2,'0')}else c.textContent='Проверяем следующие '+HORIZON+' завершённых раунда'}
function showNoSignal(best,out,rows){renderQuality(best,out);if(el('multiplier')){el('multiplier').textContent='ПРОПУСК';el('multiplier').style.color='#f4a51c'}if(el('betTime'))el('betTime').textContent='--:--';if(el('confCell'))el('confCell').textContent=pct(best?.prob);if(el('roundStatus'))el('roundStatus').textContent='0';const why=[];const m=MODES[out.mode];if(rows.length<m.minRows)why.push('история '+rows.length+'/'+m.minRows);if(best.prob<m.minP)why.push('P низкая');if(best.edge<m.minEdge)why.push('edge слабый');if(best.agreement<m.minAgree)why.push('модели не согласны');if(best.health<m.minHealth)why.push('Health '+best.health);if(best.perm.pValue>m.maxPerm)why.push('pattern похож на шум');if(best.ci.lo<m.ciFloor)why.push('CI слабый');setStatus('V2 '+out.mode+': НЕТ СИГНАЛА • '+why.join(' • ')+' • target '+best.target.toFixed(2)+'X','ko');setBridge('V2 • '+out.mode+' • ПРОПУСК • Health '+best.health)}
async function generate(){if(busy)return;if(active){cancel();return}busy=true;setMainButton();try{const st=await loadRows();lastRows=st.rows;lastState=st;renderCollect(st.rows,st.source);if(st.rows.length<ANALYZE_N)throw Error('Нужно '+ANALYZE_N+' завершённых коэффициентов');setStatus('V2: ансамбль моделей + CI + permutation test...','');await new Promise(r=>setTimeout(r,20));const out=choose(st.rows),b=out.best;lastAnalysis=out;if(!b)throw Error('Не удалось рассчитать цель');renderQuality(b,out);if(!out.pass){showNoSignal(b,out,st.rows);if(auto)setTimeout(()=>generate(),15000);return}
 const when=Date.now()+2*60*1000;active={target:b.target,prob:b.prob,baseline:b.baseline,edge:b.edge,when,round:0,anchorId:st.rows.at(-1)?.id||'',signature:st.signature,source:st.source,health:b.health,grade:b.grade,agreement:b.agreement,ciLo:b.ci.lo,ciHi:b.ci.hi,permP:b.perm.pValue,patternN:b.pattern.n,patternP:b.pattern.p,mode:out.mode};if(el('multiplier')){el('multiplier').textContent=b.target.toFixed(2)+'X';el('multiplier').style.color='#00ff66'}if(el('betTime')){el('betTime').textContent=kyiv(when);el('betTime').title='Ориентир входа по времени Украины'}if(el('confCell'))el('confCell').textContent=pct(b.prob);if(el('roundStatus'))el('roundStatus').textContent='0';const title=doc.querySelector('.meta .cell:nth-child(3) .title');if(title)title.textContent='Вероятность V2';setStatus('V2 '+out.mode+' • СТАВЬ В '+kyiv(when)+' • цель '+b.target.toFixed(2)+'X • P '+pct(b.prob)+' • edge '+(b.edge>=0?'+':'')+pct(b.edge)+' • Health '+b.health+'/100 '+b.grade+' • модели '+b.agreement+'/6','ok');const circle=el('circle');if(circle)circle.classList.add('verifying');setBridge('V2 • '+out.mode+' • '+b.target.toFixed(2)+'X • '+kyiv(when)+' • H'+b.health);startPolling();countdown()}catch(e){console.error(e);if(el('multiplier'))el('multiplier').textContent='ОШИБКА';setStatus('V2: '+(e.message||'ошибка получения данных'),'ko');setBridge('V2 • ошибка подключения')}finally{busy=false;setMainButton()}}
function cancel(){active=null;stopPolling();if(el('multiplier')){el('multiplier').textContent='0.00X';el('multiplier').style.color='#00ff66'}if(el('betTime'))el('betTime').textContent='--:--';if(el('confCell'))el('confCell').textContent='—';if(el('roundStatus'))el('roundStatus').textContent='0';if(el('countdown'))el('countdown').textContent='';const circle=el('circle');if(circle)circle.classList.remove('verifying','ok','ko');setStatus('Сигнал V2 отменён. Можно получить новый','');setMainButton();setBridge('V2 • готово')}
function finish(ok,vals){const c=counts();ok?c.ok++:c.ko++;saveCounts(c);const h=hist();h.unshift({target:active.target,status:ok?'ok':'ko',time:Date.now(),round:active.round,values:vals,prob:active.prob,baseline:active.baseline,edge:active.edge,health:active.health,grade:active.grade,agreement:active.agreement,ciLo:active.ciLo,ciHi:active.ciHi,permP:active.permP,patternN:active.patternN,patternP:active.patternP,mode:active.mode});saveHist(h);if(el('multiplier')){el('multiplier').textContent=ok?'ЗАШЛО':'НЕ ЗАШЛО';el('multiplier').style.color=ok?'#10b981':'#ef4444'}const circle=el('circle'),spin=el('spin');if(circle){circle.classList.remove('verifying','ok','ko');circle.classList.add(ok?'ok':'ko')}if(spin){spin.classList.remove('ok','ko');spin.classList.add(ok?'ok':'ko')}setStatus(ok?'V2: зашло на раунде '+active.round+' • Health '+active.health:'V2: не зашло после '+HORIZON+' раундов • Health '+active.health,ok?'ok':'ko');const wasAuto=auto;active=null;stopPolling();setMainButton();renderHistory();if(wasAuto)setTimeout(()=>generate(),3500)}
async function poll(){if(!active)return;countdown();try{const st=await loadRows();lastRows=st.rows;renderCollect(st.rows,st.source);const latest=st.rows.at(-1);if(Date.now()<active.when){active.anchorId=latest?.id||active.anchorId;active.signature=st.signature;return}let fresh=[];const idx=st.rows.findIndex(r=>r.id===active.anchorId);if(idx>=0)fresh=st.rows.slice(idx+1);else if(st.signature!==active.signature&&latest)fresh=[latest];if(!fresh.length)return;const vals=[];for(const r of fresh){active.anchorId=r.id;active.signature=st.signature;active.round++;vals.push(r.coef);if(el('roundStatus'))el('roundStatus').textContent=String(active.round);if(r.coef>=active.target){finish(true,vals);return}if(active.round>=HORIZON){finish(false,vals);return}}}catch(e){setBridge('V2 • переподключение…')}}
function startPolling(){stopPolling();pollTimer=setInterval(poll,POLL_MS);poll()}
function stopPolling(){if(pollTimer)clearInterval(pollTimer);pollTimer=null}
async function idleRefresh(){if(active||busy)return;try{const st=await loadRows();lastRows=st.rows;lastState=st;renderCollect(st.rows,st.source);if(st.rows.length>=ANALYZE_N){const out=choose(st.rows);lastAnalysis=out;renderQuality(out.best,out)}}catch{setBridge('V2 • ждём источник…')}}
function bind(){doc=FRAME.contentDocument;win=FRAME.contentWindow;if(!doc)return;const h1=doc.querySelector('h1');if(h1)h1.innerHTML='<span class="lucky">LUCKYJET </span><span class="jet">АНАЛИЗАТОР V2</span>';injectPanels();renderCounts();renderHistory();
 const gb=el('generateButton');if(gb)gb.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();generate()},true);
 const ab=el('autoButton');if(ab)ab.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();auto=!auto;ab.classList.toggle('active',auto);ab.textContent=auto?'АВТО V2: ВКЛ':'АВТОМАТ';setStatus(auto?'Автоматический режим V2 включён':'Автоматический режим V2 выключен','');if(auto&&!active)generate()},true);
 const hb=el('openHistory');if(hb)hb.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();renderHistory();openPanel('historyPanel')},true);
 const rs=el('resetStats');if(rs)rs.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();saveCounts({ok:0,ko:0});const m=el('settingsMsg');if(m)m.textContent='Статистика V2 сброшена.'},true);
 const rh=el('resetHistory');if(rh)rh.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();saveHist([]);renderHistory();const m=el('settingsMsg');if(m)m.textContent='История V2 сброшена.'},true);
 setMainButton();idleRefresh();setInterval(idleRefresh,10000);setInterval(countdown,1000);setBridge('V2 • анализ 8 • 6 моделей • CI • permutation • Health')}
FRAME.addEventListener('load',()=>{setTimeout(bind,250)});
})();