import fs from 'node:fs/promises';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const dir=new URL('../bog-hishchnik-alert/',import.meta.url);
const coreScript=await fs.readFile(new URL('ml-core.js',dir),'utf8');
const c=vm.createContext({Math,Number,Array,Object,Set});vm.runInContext(coreScript,c);const core=c.BogML;
const artifact=JSON.parse(await fs.readFile(new URL('ml-models.json',dir),'utf8'));
const parity=JSON.parse(await fs.readFile(new URL('fixtures/ml-parity.json',import.meta.url),'utf8'));
let count=0;
const check=(name,fn)=>{fn();count++;console.log('PASS '+name)};
check('Browser inference matches 1008 Python calibrated predictions for all 84 models',()=>{let largest=0;for(const row of parity){const prediction=core.predict(artifact.tasks[row.task].models[row.model],row.features);largest=Math.max(largest,Math.abs(prediction-row.probability));assert(Math.abs(prediction-row.probability)<1e-6,`${row.task} ${row.model}: ${prediction} vs ${row.probability}`);const actual=core.features(row.history);actual.forEach((v,i)=>assert(Math.abs(v-row.features[i])<1e-6))}assert.equal(parity.length,1008);console.log('max probability delta='+largest)});
check('Only past 200 coefficients generate finite features; identical inputs match',()=>{const a=Array.from({length:200},(_,i)=>1+i%17);const x=core.features(a);assert.equal(x.length,41);assert(x.every(Number.isFinite));assert.deepEqual(core.features(a),core.features([9000,...a]));assert.equal(core.features(a.slice(1)),null);a[0]=NaN;assert.equal(core.features(a),null)});
check('No model is promoted on approximate unverified source',()=>{assert.equal(Object.keys(artifact.tasks).length,21);for(const task of Object.values(artifact.tasks)){assert.equal(task.promoted,false);assert.equal(core.decision(artifact,task,{fresh:true}).promoted,false)}});
check('Stale feed, gaps and approximate clocks all block activation independently',()=>{const source={source_certified:true,actual_game_order_verified:true},task={promoted:true,reasons:[],improvement_interval:[.01,.03]};assert(core.decision(source,task,{fresh:true}).promoted);for(const quality of [{fresh:false},{fresh:true,gap:true},{fresh:true,approximate:true}])assert(!core.decision(source,task,quality).promoted)});
check('Pending and interrupted observations do not improve Brier statistics',()=>{const result=core.score([{status:'pending',probability:.9,baseline:.5,outcome:1},{status:'unknown',probability:.9,baseline:.5,outcome:1},{status:'observed',probability:.7,baseline:.5,outcome:1}]);assert.equal(result.count,1);assert(Math.abs(result.brier-.09)<1e-10);assert.equal(result.baselineBrier,.25)});
check('All train, selection, calibration and test slices have independent declared counts',()=>{for(const task of Object.values(artifact.tasks)){assert(task.counts.train>10000);assert(task.counts.select>2000);assert(task.counts.calibration>1000);assert(task.counts.test>2000);assert.equal(task.metrics.catboost.samples,task.counts.test);assert.equal(task.metrics.lightgbm.samples,task.counts.test);assert.equal(task.metrics.logistic.samples,task.counts.test)}});
check('Probability reports are finite and guarded; unsupported models fail clearly',()=>{for(const task of Object.values(artifact.tasks))for(const model of Object.values(task.models)){const p=core.predict(model,core.features(Array(200).fill(1.5)));assert(p>0&&p<1)}assert.throws(()=>core.predict({type:'invalid'},[1]));assert.throws(()=>core.predict({type:'logistic'},[NaN]))});
const client=await fs.readFile(new URL('ml-client.js',dir),'utf8');new vm.Script(client);
const html=await fs.readFile(new URL('index.html',dir),'utf8');
const full=await fs.readFile(new URL('FULL_HTML.txt',dir),'utf8');
check('New page loads real model artifacts and original one-second data transport',()=>{assert(html.includes('src="ml-core.js"'));assert(html.includes('src="ml-client.js"'));assert(html.includes('POLL_MS=1000'));assert(html.includes('BogMLClient.onFeed'));assert(html.includes('id="mlBackfill"'));assert.equal(html,full)});
console.log('PASS '+count+' ML checks');
