import fs from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const dir=fileURLToPath(new URL('../bog-hishchnik-alert/',import.meta.url));
const html=await fs.readFile(dir+'/index.html','utf8');
const mlCore=await fs.readFile(dir+'/ml-core.js','utf8');
const scripts=[...html.matchAll(/<script>([\s\S]*?)<\/script>/g)].map(m=>m[1]);
assert.equal(scripts.length,2);scripts.forEach(s=>new vm.Script(s));
const start=Date.UTC(2026,9,3,6,0),key='bog_hishchnik_ml_rules_v1';
function harness(saved=[]){
 let now=start;const requests=[],stored=new Map([[key,JSON.stringify(saved)]]),elements=new Map();
 class Clock extends Date{constructor(...args){super(...(args.length?args:[now]))}static now(){return now}}
 const node=()=>({textContent:'',innerHTML:'',children:[],value:'',style:{setProperty(){}},classList:{toggle(){}},hidden:false,disabled:false,append(...items){this.children.push(...items)},appendChild(item){this.children.push(item)},replaceChildren(...items){this.children=items},setAttribute(){},addEventListener(){},click(){}});
 const el=id=>{if(!elements.has(id))elements.set(id,node());return elements.get(id)};
 const c=vm.createContext({Date:Clock,Intl,console,Math,Number,JSON,Map,Set,Array,Object,String,URL,Blob,AbortSignal,
  document:{getElementById:el,createElement:node,addEventListener(){}},localStorage:{getItem:k=>stored.get(k),setItem:(k,v)=>stored.set(k,v)},
  setTimeout(){},clearTimeout(){},setInterval(){},fetch(url){return new Promise((resolve,reject)=>requests.push({url,resolve,reject}))}});c.window=c;
 vm.runInContext(mlCore,c);vm.runInContext(scripts[0],c);
 const end=scripts[1].lastIndexOf("restoreJournal();chooseMode('normal');");assert(end>0);
 vm.runInContext(scripts[1].slice(0,end)+`restoreJournal();globalThis.test={ordinaryAnalysis,bigOpportunity,updateAnalysis,recordSignal,processNew,evaluateJournal,renderExtras,bigDiagnostics,merge,refreshModel,checkForNewRound,archiveSelection,csvCell,chooseMode,applyLiveRound,render,fresh,
 setup(rows){merge(rows);online=true;initialized=true;lastPollAt=Date.now()},setPoll(t,ok=true){lastPollAt=t;online=ok},state(){return {rounds,signalJournal,activeNormal,activeVip,activeBig,online}},setArchive(rows){archiveRows=rows},el:$};`,c);
 return {c,app:c.test,el,requests,stored,now:()=>now,setTime:t=>now=t};
}
const rows=(values,t=start,estimated=false)=>values.map((coefficient,i)=>({id:'r'+String(i).padStart(4,'0'),coefficient,timestamp:t-i*12000,estimated}));
const respond=(req,data,total=data.length)=>req.resolve({ok:true,json:async()=>({ok:true,history:data,total})});
const flush=()=>new Promise(r=>setImmediate(r));let count=0;
async function check(name,fn){await fn();count++;console.log('PASS '+name)}
await check('Approximate history now supports a qualified cluster: 6 >=20 and 3 >=50',()=>{const h=harness();h.app.setup(rows([55,60,100,20,30,40,...Array(74).fill(2.2)],start,true));const p=h.app.bigOpportunity();assert.equal(p.target,120);assert.equal(p.score,76);assert(p.estimated);assert.equal(p.at,start+180000)});
await check('Insufficient cluster stays in observation with actual counters and time explanation',()=>{const h=harness();h.app.setup(rows([55,60,20,30,...Array(76).fill(2.2)],start,true));assert.equal(h.app.bigOpportunity(),null);const d=h.app.bigDiagnostics();assert(d.includes('— 4 (нужно 6)'));assert(d.includes('— 2 (нужно 3)'));assert(d.includes('Пуассон отключены'))});
await check('Ordinary prediction still exists for approximate history',()=>{const h=harness();h.app.setup(rows(Array(40).fill(1.5),start,true));const p=h.app.ordinaryAnalysis();assert.equal(p.target,5.25);assert.equal(p.score,70);assert(p.estimated)});
await check('Exact ordinary and big results agree with audited engine',()=>{for(const values of [Array(40).fill(1.5),[5,6,8,...Array(27).fill(2.2)],[100,60,55,45,30,25,...Array(74).fill(2.3)]]){const h=harness(),data=rows(values);h.app.setup(data);const a=h.app.ordinaryAnalysis(),b=h.c.GodPreditor.calculatePrediction(data);assert.equal(a.target,b.estimatedCoef);assert.equal(a.score,b.reliability);const big=h.app.bigOpportunity(),ref=h.c.GodPreditor.detectBigOpportunity(data,start);assert.equal(big?.target,ref?.estimatedCoef);assert.equal(big?.score,ref?.confidence)}});
await check('Approximate newest record disables exact-cycle subset even if older precise records exist',()=>{const h=harness(),data=rows(Array(40).fill(1.5));data[0].estimated=true;h.app.setup(data);assert(h.app.ordinaryAnalysis().estimated);assert.equal(h.app.ordinaryAnalysis().score,70)});
await check('Connected but stale or short history cannot produce predictions',()=>{const h=harness();h.app.setup(rows(Array(40).fill(1.5),start-86400000));assert.equal(h.app.ordinaryAnalysis(),null);assert.equal(h.app.bigOpportunity(),null);const small=harness();small.app.setup(rows([2,3]));assert.equal(small.app.ordinaryAnalysis(),null)});
await check('Invalid coefficients and conflicting IDs rejected; valid coefficients with bad clocks retained',()=>{const h=harness();h.app.setup(rows(Array(30).fill(2.2)));h.app.merge([...[null,'',true,0,-1,Infinity,NaN,'bad'].map((coefficient,i)=>({id:'bad'+i,coefficient,timestamp:start})),{id:'badtime',coefficient:2,timestamp:'bad'},{id:'future',coefficient:2,timestamp:start+60000},{id:'r0000',coefficient:100,timestamp:start}]);const data=h.app.state().rounds;assert.equal(data.length,32);assert.equal(data.find(r=>r.id==='r0000').coefficient,2.2);assert(data.find(r=>r.id==='future').estimated);assert.equal(data.find(r=>r.id==='badtime').timestamp,null)});
await check('Equal times deterministic and equal coefficients with different IDs retained',()=>{const h=harness(),data=rows([...Array(20).fill(2.2),...Array(20).fill(4)]).map(r=>({...r,timestamp:start}));const a=h.c.GodPreditor.calculatePrediction(data),b=h.c.GodPreditor.calculatePrediction(data.reverse());assert.equal(a.estimatedCoef,b.estimatedCoef);h.app.setup(data);assert.equal(h.app.state().rounds.length,40)});
await check('Targets fixed across mode changes and newly merged rounds',()=>{const h=harness();h.app.setup(rows(Array(40).fill(1.5)));h.app.updateAnalysis(true);const p=h.app.state().activeNormal;h.app.chooseMode('vip');h.setTime(start+1000);h.app.merge([{id:'new',coefficient:100,timestamp:start+1000}]);h.app.updateAnalysis(true);assert.equal(h.app.state().activeNormal,p);assert.equal(p.target,5.25)});
await check('Fourth eligible round can hit, duplicate and outside-window rounds excluded',()=>{const h=harness();h.app.setup(rows(Array(40).fill(1.5)));h.app.updateAnalysis(true);const s=h.app.state().signalJournal.find(x=>x.kind==='normal');h.setTime(s.at+5000);const low=[1,2,3].map(i=>({id:'new'+i,coefficient:1.1,timestamp:s.at+i*1000,estimated:false}));h.app.processNew([...low,low[0],{id:'early',coefficient:100,timestamp:s.at-1},{id:'late',coefficient:100,timestamp:s.at+s.window+1}]);assert.equal(s.checked,3);h.app.processNew([{id:'fourth',coefficient:6,timestamp:s.at+4000,estimated:false}]);assert.equal(s.status,'hit')});
await check('Approximate observations excluded from confirmed hits',()=>{const h=harness();h.app.setup(rows(Array(40).fill(1.5)));h.app.updateAnalysis(true);const s=h.app.state().signalJournal.find(x=>x.kind==='normal');h.setTime(s.at+1000);h.app.processNew([{id:'observed',coefficient:6,timestamp:s.at+1000,estimated:true}]);assert.equal(s.status,'observed');h.app.renderExtras();assert(h.el('signalStats').textContent.includes('попадания: 0'));assert(h.el('signalStats').textContent.includes('время ≈: 1'))});
await check('Miss requires precise round after end and final complete poll',()=>{const h=harness();h.app.setup(rows(Array(40).fill(1.5)));h.app.updateAnalysis(true);const s=h.app.state().signalJournal.find(x=>x.kind==='normal'),end=s.at+s.window;h.setTime(s.at+1000);h.app.processNew([{id:'low',coefficient:1.1,timestamp:s.at+1000,estimated:false}]);h.setTime(end+31000);h.app.merge([{id:'end',coefficient:1.1,timestamp:end+31000,estimated:false}]);h.app.setPoll(h.now());h.app.evaluateJournal();assert.equal(s.status,'miss')});
await check('Stalled source and missing coverage cannot become a miss',()=>{for(const offline of [false,true]){const h=harness();h.app.setup(rows(Array(40).fill(1.5)));h.app.updateAnalysis(true);const s=h.app.state().signalJournal.find(x=>x.kind==='normal'),end=s.at+s.window;h.setTime(end-1000);h.app.merge([{id:'last',coefficient:1.1,timestamp:end-1000,estimated:false}]);h.app.processNew([{id:'last',coefficient:1.1,timestamp:end-1000,estimated:false}]);h.setTime(end+91000);h.app.setPoll(h.now(),!offline);h.app.evaluateJournal();assert.equal(s.status,'expired')}});
await check('Reload restores fixed active signal and marks coverage gap',()=>{const signal={target:3,score:70,at:start+30000,window:120000,generatedAt:start};const h=harness([{id:'normal:'+start,kind:'normal',signal,status:'pending',ids:[]}]);assert.equal(h.app.state().activeNormal.target,3);assert(h.app.state().signalJournal[0].coverageGap)});
await check('Malformed local storage does not corrupt render',()=>{const h=harness([{kind:'normal',signal:{target:3,score:'bad',at:start,window:150000}},{kind:'big',signal:{target:3,score:70,at:start,window:-1,generatedAt:start}}]);assert.equal(h.app.state().signalJournal.length,0);h.app.renderExtras()});
await check('Fast and full requests share single flight; late snapshot keeps fresh round',async()=>{const h=harness();h.app.setup(rows(Array(40).fill(2.2)));const a=h.app.refreshModel(),b=h.app.checkForNewRound();assert.equal(a,b);assert.equal(h.requests.length,1);h.setTime(start+1000);h.app.merge([{id:'newer',coefficient:4,timestamp:start+1000}]);respond(h.requests[0],rows(Array(40).fill(2.2)));await a;assert.equal(h.app.state().rounds[0].id,'newer')});
await check('API cap 1000 fills 2000 through pagination and rereads head',async()=>{const h=harness(),all=rows(Array(2000).fill(2.2));const promise=h.app.refreshModel();respond(h.requests[0],all.slice(0,1000),4000);await flush();assert(h.requests[1].url.includes('offset=1000'));respond(h.requests[1],all.slice(1000),4000);await flush();assert(h.requests[2].url.includes('limit=100'));respond(h.requests[2],all.slice(0,100),4000);await promise;assert.equal(h.app.state().rounds.length,2000)});
await check('Calendar-day archive filtering uses local timezone and keeps identical coefficients',()=>{const h=harness(),ts=Date.UTC(2026,9,2,21,30);h.app.setArchive([{id:'a',coefficient:2,timestamp:ts},{id:'b',coefficient:2,timestamp:ts+1000}]);h.el('archiveDate').value='2026-10-03';h.el('archiveMin').value='2';assert.equal(h.app.archiveSelection().length,2);h.el('archiveDate').value='2026-10-05';assert.equal(h.app.archiveSelection().length,0);assert.equal(h.app.csvCell('=bad'),`"'=bad"`)});
await check('Four-field analysis panel has no false neural-network claim and export is current',async()=>{assert(html.includes('Ориентировочная цель'));assert(html.includes('Уровень оценки'));assert(html.includes('Оценка правил'));assert(html.includes('Начало наблюдения'));assert(html.includes('отдельная нейросеть не подключена'));assert.equal(await fs.readFile(dir+'/FULL_HTML.txt','utf8'),html)});
await check('All 170 future-clock coefficients retained; next new batch appears immediately',async()=>{const h=harness(),valid=rows(Array(1830).fill(2.2)),future=rows(Array(170).fill(5),start+7200000,true).map((r,i)=>({...r,id:'future'+i}));const promise=h.app.refreshModel();respond(h.requests[0],[...future,...valid.slice(0,830)],5000);await flush();respond(h.requests[1],valid.slice(830),5000);await flush();respond(h.requests[2],future.slice(0,100),5000);await promise;assert.equal(h.app.state().rounds.length,2000);assert.equal(h.app.state().rounds.filter(r=>r.timeIssue==='clock').length,170);assert(!h.app.fresh());h.setTime(start+1000);const fast=h.app.checkForNewRound();assert(h.requests[3].url.includes('limit=270'));const batch=[{id:'next-a',coefficient:80,timestamp:start+7201000},{id:'next-b',coefficient:80,timestamp:start+7200500}];respond(h.requests[3],[...batch,...future.slice(0,100)],5002);await fast;assert.deepEqual(Array.from(h.app.state().rounds.slice(0,2),r=>r.id),['next-a','next-b']);assert(h.app.fresh());assert(h.app.ordinaryAnalysis().estimated);h.setTime(start+181001);assert(!h.app.fresh())});
await check('WebSocket keeps new results even without a timestamp and does not replay snapshot as a hit',()=>{const h=harness();h.app.setup(rows(Array(40).fill(1.5)));h.app.updateAnalysis(true);const s=h.app.state().signalJournal.find(x=>x.kind==='normal');h.setTime(s.at+1000);h.app.merge([{id:'history',coefficient:80,timestamp:start+7200000}]);h.app.processNew(h.app.state().rounds.filter(r=>r.id==='history'));assert.equal(s.status,'pending');h.app.applyLiveRound({id:'received',coefficient:80});assert.equal(h.app.state().rounds[0].id,'received');assert.equal(s.status,'observed');assert(s.approximate);h.app.applyLiveRound({id:'received',coefficient:80});assert.equal(h.app.state().rounds.filter(r=>r.id==='received').length,1)});
await check('Correct-clock result behind skewed head is fetched and promoted to live head',async()=>{const h=harness(),future=rows(Array(170).fill(2.2),start+7200000,true).map((r,i)=>({...r,id:'future'+i})),past=rows(Array(100).fill(1.5));h.app.setup([...future,...past]);h.setTime(start+1000);const promise=h.app.checkForNewRound();assert(h.requests[0].url.includes('limit=270'));respond(h.requests[0],[...future,{id:'correct-clock-new',coefficient:42,timestamp:start+1000},...past.slice(0,99)],10000);await promise;assert.equal(h.app.state().rounds[0].id,'correct-clock-new');assert(h.app.fresh())});
await check('A repeated poll and backfilled old rows never manufacture freshness',async()=>{const h=harness(),future=rows(Array(30).fill(2.2),start+7200000,true).map((r,i)=>({...r,id:'future'+i}));h.app.setup(future);const promise=h.app.checkForNewRound();respond(h.requests[0],[...future,...rows(Array(30).fill(2.2),start-86400000)],1000);await promise;assert(!h.app.fresh());assert(h.app.state().rounds.every(r=>!r._observedAt));assert.equal(h.app.ordinaryAnalysis(),null)});
await check('Source matches beta, 1-second polling and complete batch backfill beyond 100 rows',async()=>{const contract=JSON.parse(await fs.readFile(new URL('./fixtures/beta-source-contract.json',import.meta.url),'utf8'));const api=contract.api;assert(html.includes(api));assert(html.includes('POLL_MS=1000'));assert(html.includes('setInterval(checkForNewRound,POLL_MS)'));assert(html.includes('setInterval(refreshModel,30000)'));const h=harness(),old=rows(Array(500).fill(2.2)),batch=rows(Array(140).fill(80),start+1000,true).map((r,i)=>({...r,id:'batch'+i}));h.app.setup(old);h.setTime(start+1000);const promise=h.app.checkForNewRound();respond(h.requests[0],batch.slice(0,100),640);await flush();respond(h.requests[1],[...batch,...old],640);await promise;assert.equal(h.app.state().rounds.filter(r=>r.id.startsWith('batch')).length,140);assert.equal(h.app.state().rounds.length,640)});
console.log('PASS '+count+' scenarios · TZ '+process.env.TZ);

