const API="https://crash-gateway-grm-cr.100hp.app/history",CID="077dee8d-c923-4c02-9bee-757573662e69",E=(document.body.dataset.engine||"h23-fusion").toLowerCase(),$=id=>document.getElementById(id);
let rounds=[],seen=new Set(),newest=null,pending=null,w=0,l=0;
const N={"babel-v6":"Babel V6","gamehub-pro":"GameHub PRO","gamehub-premium":"GameHub Premium","gamehub-montante":"GameHub Montante","gamehub-hack":"GameHub Hack Context","jean-adaptive":"JeanIvna Adaptive","jean-fixed-ultimate":"JeanIvna Fixed Ultimate","jean-ultimate-enhanced":"JeanIvna Ultimate Enhanced","jean-ultra-realtime":"JeanIvna Ultra Real-Time","h23-fusion":"🏆 H23 FUSION"};
function sid(){let s=localStorage.getItem("LJ_SESSION_ID")||"";if(!s){s=(prompt("Введите LuckyJet session-id для LIVE /history:")||"").trim();if(s)localStorage.setItem("LJ_SESSION_ID",s)}return s}
function resetSid(){localStorage.removeItem("LJ_SESSION_ID");location.reload()}
function norm(x){if(!x||typeof x!=="object")return null;let c=Number(x.topCoefficient);if(!Number.isFinite(c)||c<=0){let a=Array.isArray(x.finalValues)?x.finalValues.map(Number).filter(v=>Number.isFinite(v)&&v>0):[];if(a.length)c=a[a.length-1]}if(!Number.isFinite(c)||c<=0)return null;if(c===1)c=1.01;c=Math.round(c*100)/100;return{id:String(x.id||x.roundId||x.round_id||x.hash||("r:"+c+":"+(x.createdAt||x.time||""))),c}}
const mean=a=>a.length?a.reduce((s,x)=>s+x,0)/a.length:0,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function med(a){if(!a.length)return 0;let s=[...a].sort((x,y)=>x-y),m=Math.floor(s.length/2);return s.length%2?s[m]:(s[m-1]+s[m])/2}
function sd(a){if(a.length<2)return 0;let m=mean(a);return Math.sqrt(mean(a.map(x=>(x-m)**2)))}
function ema(a,k=.22){if(!a.length)return 0;let e=a[a.length-1];for(let i=a.length-2;i>=0;i--)e=a[i]*k+e*(1-k);return e}
function slope(a){if(a.length<2)return 0;let y=[...a].reverse(),n=y.length,sx=0,sy=0,sxy=0,sxx=0;for(let i=0;i<n;i++){let x=i+1;sx+=x;sy+=y[i];sxy+=x*y[i];sxx+=x*x}let d=n*sxx-sx*sx;return d?(n*sxy-sx*sy)/d:0}
function pos(a,fn){let p=[];a.forEach((x,i)=>{if(fn(x))p.push(i)});return p}
function gaps(p){let a=[];for(let i=1;i<p.length;i++)a.push(p[i]-p[i-1]);return a}
function entropy(a){let b=[0,0,0,0,0];a.slice(0,50).forEach(c=>{if(c<1.3)b[0]++;else if(c<2)b[1]++;else if(c<5)b[2]++;else if(c<10)b[3]++;else b[4]++});let n=b.reduce((s,x)=>s+x,0);if(!n)return 0,h=0;b.forEach(x=>{if(x){let p=x/n;h-=p*Math.log(p)}});return h/Math.log(5)}
function cyc(a){let best=0,c=a.map(x=>Math.min(x,20));for(let len=2;len<=8;len++){if(c.length<len*2)continue;let x=c.slice(0,len),y=c.slice(len,len*2),sc=Math.max(1,mean(x.concat(y))),d=mean(x.map((v,i)=>Math.abs(v-y[i])/sc));best=Math.max(best,clamp(1-d,0,1))}return best}
function bayes(a,t){let z=a.slice(0,60),s=z.filter(x=>x>=t).length;return(1+s)/(2+z.length)}
function M(){let a=rounds.map(x=>x.c),r8=a.slice(0,8),r10=a.slice(0,10),r20=a.slice(0,20),clip=r20.map(x=>Math.min(x,20)),p10=pos(a,x=>x>=10),gm=pos(a,x=>x>=1.2&&x<=1.5),g10=gaps(p10),gM=gaps(gm),v=sd(clip)/Math.max(mean(clip),1),sl=slope(r10.map(x=>Math.min(x,15))),en=entropy(a),cy=cyc(a),b2=bayes(a,2);let big=r20.filter(x=>x>=10).length,small=r20.filter(x=>x>=1.2&&x<=1.5).length,reg=big>=3?"big":small>=6?"small":en>.86?"chaotic":Math.abs(sl)>.35?"trending":"mixed";return{a,r8,r10,r20,mean:mean(clip),ema:ema(clip),vol:v,slope:sl,entropy:en,cycle:cy,b2,regime:reg,gap10:p10.length?p10[0]:a.length,med10:med(g10)||12,gapM:gm.length?gm[0]:a.length,medM:med(gM)||5,low:a.slice(0,10).filter(x=>x<2).length}}
function base(m){let raw=m.ema*.6+m.mean*.3+(m.a[0]||1)*.1;if(m.slope>.12)raw*=1.04;if(m.slope<-.12)raw*=.97;let margin=raw<2?.15:raw<3?.25:.35;return{target:clamp(raw*(1-margin),1.2,8),conf:clamp(Math.round((1-Math.min(1,m.vol/1.5))*100),20,94)}}
function pred(){if(rounds.length<8)return{kind:"wait",text:"СБОР ДАННЫХ…",meta:`${rounds.length}/8 LIVE раундов`};let m=M(),p=base(m),target=1.5,score=50,window=3;
if(E==="babel-v6"){target=clamp(mean(m.a.slice(0,3))*1.10,1.2,2.4);score=48;window=1}
else if(E==="gamehub-pro"){target=p.target;score=clamp(Math.round(p.conf*.65+Math.min(1,Math.abs(m.slope)/.25)*20+(m.slope>0?10:5)),20,94)}
else if(E==="gamehub-premium"){target=clamp(p.target,1.2,12);score=clamp(Math.round(p.conf*.55+Math.min(1,Math.abs(m.slope)/.25)*25+(m.slope>0?12:6)),0,100);if(score<55)return{kind:"skip",text:"⏸ ПРОПУСК",meta:`Premium score ${score}/100`}}
else if(E==="gamehub-montante"){let low=m.r8.filter(x=>x<1.5).length;score=clamp(Math.round(45+low*6+(m.mean<2?8:0)-m.r8.filter(x=>x>=5).length*8),20,90);target=score>=75?1.5:1.3;window=1;if(score<58)return{kind:"skip",text:"⏸ ПРОПУСК",meta:`Montante ${score}/100`}}
else if(E==="gamehub-hack"){score=clamp(Math.round(48+m.low*3+(m.regime==="mixed"?8:0)-(m.regime==="chaotic"?12:0)+(1-Math.min(m.vol,1))*10),15,92);target=clamp(p.target*.92,1.35,3.5);if(score<57)return{kind:"skip",text:"⏸ РЫНОК ПЛОХОЙ",meta:`Context ${score}/100 · ${m.regime}`}}
else if(E==="jean-adaptive"){score=clamp(Math.round(44+m.cycle*18+Math.min(1.5,m.gap10/m.med10)*12+(1-Math.min(m.vol,1))*12),15,94);target=clamp(p.target*.90,1.3,4);if(score<58)return{kind:"skip",text:"⏸ АДАПТИВНЫЙ ПРОПУСК",meta:`${score}/100 · cycle ${m.cycle.toFixed(2)}`}}
else if(E==="jean-fixed-ultimate"){score=clamp(Math.round(40+m.cycle*16+Math.min(1.5,m.gap10/m.med10)*15+(m.b2-.5)*18-(m.vol>1.4?8:0)),10,95);target=clamp(p.target*.88,1.3,5);if(score<61)return{kind:"skip",text:"⏸ ULTIMATE ПРОПУСК",meta:`${score}/100 · gap10 ${m.gap10}/${m.med10.toFixed(1)}`}}
else if(E==="jean-ultimate-enhanced"){let adv=m.cycle*.32+m.b2*.28+(1-m.entropy)*.40;score=clamp(Math.round(42+adv*35+Math.min(1.5,m.gap10/m.med10)*10-(m.vol>1.5?6:0)),10,95);target=clamp(p.target*(.88+adv*.05),1.3,5.5);if(score<62)return{kind:"skip",text:"⏸ ENSEMBLE ПРОПУСК",meta:`${score}/100 · advanced ${adv.toFixed(2)}`}}
else if(E==="jean-ultra-realtime"){let mom=clamp(m.slope/1.5,-1,1),q=(1-m.entropy)*.35+m.cycle*.25+m.b2*.40;score=clamp(Math.round(43+q*30+mom*6+(m.regime==="mixed"?6:0)-(m.regime==="chaotic"?8:0)),10,95);target=clamp(p.target*(.90+mom*.03),1.3,5);if(score<60)return{kind:"skip",text:"⏸ REAL-TIME ПРОПУСК",meta:`${score}/100 · ${m.regime} · entropy ${m.entropy.toFixed(2)}`}}
else{let gap=clamp(m.gap10/m.med10,0,1.7),adv=m.cycle*.25+m.b2*.25+(1-m.entropy)*.25+clamp(1-m.vol/1.5,0,1)*.25;score=clamp(Math.round(40+gap*12+adv*35+(m.regime==="mixed"?5:0)-(m.regime==="chaotic"?8:0)),10,96);target=clamp(p.target*(.86+adv*.04),1.35,4.5);if(score<63)return{kind:"skip",text:"⏸ FUSION ПРОПУСК",meta:`${score}/100 · gap10 ${m.gap10}/${m.med10.toFixed(1)} · ${m.regime}`}}
return{kind:"go",target:Math.round(target*100)/100,score,window,text:`🎯 ${target.toFixed(2)}X`,meta:`${N[E]} · ${score}/100 · проверка ${window} раунд(а/ов)`}}
function render(){$("engine").textContent=N[E]||E;$("chips").innerHTML=rounds.slice(0,16).map(x=>`<span class="chip">${x.c.toFixed(2)}X</span>`).join("")||"Ожидание…";$("wins").textContent=w;$("losses").textContent=l;$("total").textContent=w+l;if(!pending){let p=pred();$("sig").textContent=p.text;$("meta").textContent=p.meta;if(p.kind==="go")pending={target:p.target,left:p.window,window:p.window}}}
function check(c){if(!pending)return;if(c>=pending.target){w++;$("verify").textContent=`✅ ЗАШЛО · цель ${pending.target.toFixed(2)}X · выпало ${c.toFixed(2)}X`;pending=null;return}if(--pending.left<=0){l++;$("verify").textContent=`❌ НЕ ЗАШЛО · цель ${pending.target.toFixed(2)}X`;pending=null}}
async function tick(){try{let s=sid();if(!s)throw Error("session-id не указан");let r=await fetch(API,{headers:{"customer-id":CID,"session-id":s,"accept":"application/json"},cache:"no-store"});if(!r.ok)throw Error("HTTP "+r.status);let data=await r.json(),list=data.map(norm).filter(Boolean);if(!newest){rounds=list.slice(0,200);seen=new Set(rounds.map(x=>x.id));newest=rounds[0]?.id}else{let fresh=[];for(let x of list){if(x.id===newest)break;if(!seen.has(x.id))fresh.push(x)}if(fresh.length){fresh.reverse().forEach(x=>{check(x.c);rounds.unshift(x);seen.add(x.id);render()});newest=list[0].id;rounds=rounds.slice(0,200)}}$("api").textContent=`✅ LIVE /history · ${list.length} раундов`;render()}catch(e){$("api").textContent="❌ "+String(e.message||e)}setTimeout(tick,1200)}
document.addEventListener("DOMContentLoaded",()=>{$("reset").addEventListener("click",resetSid);render();tick()});