-- AllPredictor fresh-project schema.
-- Safe to run more than once; no test users or licenses are inserted.

create extension if not exists pgcrypto;

create table if not exists public.app_users (
  telegram_id bigint primary key,
  username text,
  first_name text,
  last_name text,
  language_code text,
  first_seen_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  launch_count integer not null default 1,
  is_blocked boolean not null default false,
  referral_code text unique,
  referred_by text,
  metadata jsonb not null default '{}'::jsonb
);

create table if not exists public.license_keys (
  id uuid primary key default gen_random_uuid(),
  license_key text unique not null,
  plan text not null check (plan in ('pro_1','pro_7','pro_30','pro_90','lifetime')),
  duration_days integer,
  max_devices integer not null default 1,
  max_activations integer not null default 1,
  activation_count integer not null default 0,
  bound_telegram_id bigint references public.app_users(telegram_id) on delete set null,
  status text not null default 'active' check (status in ('active','revoked','used','expired')),
  created_at timestamptz not null default now(),
  expires_at timestamptz,
  activated_at timestamptz,
  note text,
  created_by bigint
);

create table if not exists public.license_activations (
  id uuid primary key default gen_random_uuid(),
  license_id uuid not null references public.license_keys(id) on delete cascade,
  telegram_id bigint not null references public.app_users(telegram_id) on delete cascade,
  activation_token text unique not null default encode(gen_random_bytes(32), 'hex'),
  device_hash text not null,
  activated_at timestamptz not null default now(),
  last_checked_at timestamptz not null default now(),
  expires_at timestamptz,
  is_active boolean not null default true
);

create table if not exists public.app_events (
  id bigint generated always as identity primary key,
  telegram_id bigint references public.app_users(telegram_id) on delete set null,
  event_name text not null,
  page text,
  game text,
  created_at timestamptz not null default now(),
  data jsonb not null default '{}'::jsonb
);

create table if not exists public.referrals (
  id bigint generated always as identity primary key,
  referrer_telegram_id bigint references public.app_users(telegram_id) on delete cascade,
  referred_telegram_id bigint unique references public.app_users(telegram_id) on delete cascade,
  referral_code text not null,
  created_at timestamptz not null default now(),
  reward_granted boolean not null default false
);

create table if not exists public.notification_log (
  id bigint generated always as identity primary key,
  telegram_id bigint not null references public.app_users(telegram_id) on delete cascade,
  notification_type text not null,
  reference_id text,
  sent_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb,
  unique (telegram_id, notification_type, reference_id)
);

create table if not exists public.beta_ai_rounds (
  id bigint generated by default as identity primary key,
  round_key text not null unique,
  coefficient numeric(12,2) not null,
  source_time text,
  raw jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.beta_ai_signals (
  id bigint generated by default as identity primary key,
  target numeric(12,2) not null,
  status text not null default 'open' check (status in ('open','win','loss')),
  checked_rounds integer not null default 0,
  result_coefficient numeric(12,2),
  source_round_id bigint references public.beta_ai_rounds(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists idx_app_users_last_seen on public.app_users(last_seen_at desc);
create index if not exists idx_license_keys_status on public.license_keys(status);
create index if not exists idx_license_activations_token on public.license_activations(activation_token);
create unique index if not exists license_activation_device_unique
  on public.license_activations (license_id, telegram_id, device_hash);
create index if not exists idx_license_activation_user_devices
  on public.license_activations (license_id, telegram_id, is_active);
create index if not exists idx_app_events_created on public.app_events(created_at desc);
create index if not exists idx_notification_log_sent_at on public.notification_log(sent_at desc);
create index if not exists beta_ai_rounds_created_idx on public.beta_ai_rounds(created_at desc);
create index if not exists beta_ai_signals_created_idx on public.beta_ai_signals(created_at desc);
create unique index if not exists beta_ai_one_open_signal
  on public.beta_ai_signals ((status)) where status = 'open';

alter table public.app_users enable row level security;
alter table public.license_keys enable row level security;
alter table public.license_activations enable row level security;
alter table public.app_events enable row level security;
alter table public.referrals enable row level security;
alter table public.notification_log enable row level security;
alter table public.beta_ai_rounds enable row level security;
alter table public.beta_ai_signals enable row level security;

revoke all on public.app_users from anon, authenticated;
revoke all on public.license_keys from anon, authenticated;
revoke all on public.license_activations from anon, authenticated;
revoke all on public.app_events from anon, authenticated;
revoke all on public.referrals from anon, authenticated;
revoke all on public.notification_log from anon, authenticated;

drop policy if exists "beta ai public read rounds" on public.beta_ai_rounds;
create policy "beta ai public read rounds"
  on public.beta_ai_rounds for select using (true);
drop policy if exists "beta ai public read signals" on public.beta_ai_signals;
create policy "beta ai public read signals"
  on public.beta_ai_signals for select using (true);
grant select on public.beta_ai_rounds, public.beta_ai_signals to anon, authenticated;

create or replace function public.make_license_key(prefix text default 'V0X')
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  candidate text;
  seed text;
begin
  loop
    seed := md5(
      random()::text
      || clock_timestamp()::text
      || txid_current()::text
      || pg_backend_pid()::text
    );
    candidate := upper(coalesce(nullif(trim(prefix), ''), 'V0X'))
      || '-' || upper(substr(seed, 1, 4))
      || '-' || upper(substr(seed, 5, 4))
      || '-' || upper(substr(seed, 9, 4));
    exit when not exists (
      select 1 from public.license_keys where license_key = candidate
    );
  end loop;
  return candidate;
end;
$$;

drop function if exists public.create_license(text, integer, integer, text, bigint);
create function public.create_license(
  p_plan text,
  p_duration_days integer default null,
  p_max_activations integer default 1,
  p_note text default null,
  p_created_by bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  created_row public.license_keys;
  effective_days integer;
  device_limit integer;
begin
  if p_plan not in ('pro_1','pro_7','pro_30','pro_90','lifetime') then
    raise exception 'INVALID_PLAN';
  end if;

  effective_days := case
    when p_plan = 'lifetime' then null
    when p_duration_days is not null then least(3650, greatest(1, p_duration_days))
    when p_plan = 'pro_1' then 1
    when p_plan = 'pro_7' then 7
    when p_plan = 'pro_90' then 90
    else 30
  end;
  device_limit := least(2, greatest(1, coalesce(p_max_activations, 1)));

  insert into public.license_keys (
    license_key, plan, duration_days, max_devices, max_activations,
    activation_count, status, note, created_by
  ) values (
    public.make_license_key('V0X'), p_plan, effective_days, device_limit,
    device_limit, 0, 'active', nullif(trim(coalesce(p_note, '')), ''),
    p_created_by
  ) returning * into created_row;

  return to_jsonb(created_row);
end;
$$;

revoke all on function public.create_license(text, integer, integer, text, bigint)
  from public, anon, authenticated;
grant execute on function public.create_license(text, integer, integer, text, bigint)
  to service_role;

notify pgrst, 'reload schema';
